version: 0.2

phases:
  install:
    command:
      - curl https://releases.hashicorp.com/terraform/1.6.3/terraform_1.6.3_linux_amd64.zip
      - sudo apt install unzip
      - unzip terraform_1.6.3_linux_amd64.zip
      - mv terraform /user/local/bin/
      - terraform --version
      
  build:
    command:  
      - terraform init
      - terraform plan
      - terraform apply
      
   
